[profile.default]
src = "lib/cmta/contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

remappings = [
  '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
  '@chainlink/contracts/=node_modules/@chainlink/contracts/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/cmta/node_modules/@openzeppelin/contracts-upgradeable/',
  '@openzeppelin/contracts@4.8.3/=node_modules/@openzeppelin/contracts-4.8.3/',
  '@openzeppelin/contracts@5.0.2/=node_modules/@openzeppelin/contracts-5.0.2/'
]

fs_permissions = [{ access = "read-write", path = "./" }]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
fuji = "${FUJI_RPC}"
[etherscan]
sepolia = { key = "${ETHERSCAN_TOKEN}", chain = 11155111, url = "https://api.etherscan.io/v2/api?chainid=11155111" }
fuji = { key = "${SNOWTRACE_TOKEN}", chain = 43113, url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan" }
